version: "3"
services:
  tm-proxy:
    build: .
    container_name: tm-proxy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      - TS_AUTHKEY=$TS_AUTHKEY
      - TS_VERBOSE=1
      - TS_LOGIN_SERVER=$TS_LOGIN_SERVER
    network_mode: host
    restart: unless-stopped

  httpd:
    container_name: httpd
    image: httpd
    networks:
      expose:
        ipv4_address: 172.24.0.11

volumes:
  timemachine-var-lib-samba:
  timemachine-var-cache-samba:
  timemachine-run-samba:

networks:
  expose:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/24
