version: "3"
services:
  tm-proxy:
    build: .
    container_name: user1-tm-proxy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    environment:
      - TS_AUTHKEY=$TS_AUTHKEY
      - TS_VERBOSE=1
      - TS_LOGIN_SERVER=$TS_LOGIN_SERVER
    network_mode: host
    restart: unless-stopped

  httpd:
    image: httpd
    ports:
      - 127.0.0.1:8081:80

volumes:
  timemachine-var-lib-samba:
  timemachine-var-cache-samba:
  timemachine-run-samba:
