version: "3"
services:
  tm-proxy:
    build: .
    container_name: tm-proxy
    command: caddy run --config /etc/caddy/config.json
    volumes:
      - ./config.json:/etc/caddy/config.json:ro
    environment:
      - TS_AUTHKEY_TM_1=$TS_AUTHKEY_TM_1
      - TS_AUTHKEY_TM_2=$TS_AUTHKEY_TM_2
      - TS_VERBOSE=1
      - TS_LOGIN_SERVER=$TS_LOGIN_SERVER
    network_mode: host
    restart: unless-stopped

  tm-1:
    image: mbentley/timemachine:smb
    container_name: tm-1
    volumes:
      - $TM_PATH/tm-1:/opt/timemachine
      - ./smb.conf:/etc/samba/smb.conf
      - timemachine-var-lib-samba:/var/lib/samba
      - timemachine-var-cache-samba:/var/cache/samba
      - timemachine-run-samba:/run/samba
    environment:
      - DEBUG_LEVEL=2
      - CUSTOM_SMB_CONF=true
    networks:
      expose:
        ipv4_address: 172.24.0.11
    restart: unless-stopped

  tm-2:
    image: mbentley/timemachine:smb
    container_name: tm-2
    volumes:
      - $TM_PATH/tm-2:/opt/timemachine
      - ./smb.conf:/etc/samba/smb.conf
      - timemachine-var-lib-samba:/var/lib/samba
      - timemachine-var-cache-samba:/var/cache/samba
      - timemachine-run-samba:/run/samba
    environment:
      - DEBUG_LEVEL=2
      - CUSTOM_SMB_CONF=true
    networks:
      expose:
        ipv4_address: 172.24.0.12
    restart: unless-stopped

volumes:
  timemachine-var-lib-samba:
  timemachine-var-cache-samba:
  timemachine-run-samba:

networks:
  expose:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/24
